// ─── CONFIGURACIÓN DE PUNTO 25 DELIVERY ───────────────────────────────────
const WA_NUMBERS = ['3813253754', '3813980410']; // Celulares del folleto
const INSTAGRAM_USER = 'punto25delivery';
const ADDRESS_TEXT = 'Corrientes 664, Barrio Norte';
// Pegar aquí la URL del Web App obtenida al desplegar el script en Google Apps Script:

const GOOGLE_SHEETS_URL = 'https://script.google.com/macros/s/AKfycbxPBn2bWx4mr8Csru-FLmcejJaqq_vQwDmvK9u_4snMTs09vP7jrok7LNw5IFnK2UStSw/exec'; // URL real de Google Apps Script provista por el cliente

const MENU = [
  // ── COLUMNA IZQUIERDA: REBOZADOS Y GRANJA DE POLLO ──────────────────────────
  {
    id: 1,
    cat: 'pollo-rebozado',
    name: 'Patitas',
    desc: 'Clásicas patitas rebozadas súper crocantes, elaboradas con pura pechuga de pollo.',
    ingredients: 'Pechuga de pollo fresca y rebozado crujiente de pan.',
    prepDesc: 'Preparación express. Ideal para freír en aceite caliente o dorar al horno a 200°C por 15 minutos.',
    prepTime: '15 min',
    price: 14900,
    priceHalf: 7900,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400&auto=format&fit=crop&q=80',
    emoji: '🍗',
    tags: ['popular', 'niños'],
    hot: true,
    rating: 4.9
  },
  {
    id: 2,
    cat: 'pollo-rebozado',
    name: 'Patitas con jamón y queso',
    desc: 'Exquisitas patitas crujientes rellenas con jamón cocido seleccionado y queso derretido.',
    ingredients: 'Pechuga de pollo seleccionada, jamón cocido de primera, queso mozzarella hilado, rebozado premium.',
    prepDesc: 'Recomendado al horno a 180°C por 18 minutos para que el queso funda perfectamente sin desbordar.',
    prepTime: '18 min',
    price: 14900,
    priceHalf: 7900,
    unitType: 'peso',
    img: '',
    emoji: '🧀',
    tags: ['popular', 'relleno'],
    hot: false,
    rating: 4.8
  },
  {
    id: 3,
    cat: 'pollo-rebozado',
    name: 'Crocantes de Pollo ( Nuggets)',
    desc: 'Bocaditos de pechuga de pollo rebozados con un rebozado extra crujiente y dorado.',
    ingredients: 'Pechuga de pollo cortada a mano, mix especial de rebozado con cereales, ajo y perejil.',
    prepDesc: 'Freír en abundante aceite caliente por 5 minutos o dorar al horno a temperatura máxima por 12 minutos.',
    prepTime: '12 min',
    price: 15900,
    priceHalf: 8500,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=400&auto=format&fit=crop&q=80',
    emoji: '🍗',
    tags: ['crocante'],
    hot: true,
    rating: 4.9
  },
  {
    id: 4,
    cat: 'pollo-rebozado',
    name: 'Medallones de Pollo',
    desc: 'Prácticos y deliciosos medallones de pollo listos para una comida rápida.',
    ingredients: 'Pura carne de pechuga procesada y rebozado clásico.',
    prepDesc: 'Cocinar directamente a la plancha lubricada o al horno por 15 minutos girándolos a mitad de cocción.',
    prepTime: '15 min',
    price: 14900,
    priceHalf: 7900,
    unitType: 'peso',
    img: '',
    emoji: '💿',
    tags: ['exprés'],
    hot: false,
    rating: 4.6
  },
  {
    id: 5,
    cat: 'pollo-rebozado',
    name: 'Medallones de Pollo con jamón y queso',
    desc: 'Medallones tiernos rellenos de abundante jamón cocido y queso mozzarella fundente.',
    ingredients: 'Pechuga de pollo, centro de jamón cocido en fetas y mozzarella, rebozado tradicional.',
    prepDesc: 'Hornear a temperatura media (190°C) por 20 minutos hasta que el rebozado tome un color dorado.',
    prepTime: '20 min',
    price: 14900,
    priceHalf: 7900,
    unitType: 'peso',
    img: '',
    emoji: '🧀',
    tags: ['relleno'],
    hot: false,
    rating: 4.7
  },
  {
    id: 6,
    cat: 'pollo-rebozado',
    name: 'Medallones de Pollo con espinacas y queso',
    desc: 'Combinación saludable de pollo con hojas de espinaca fresca y suave queso mozzarella.',
    ingredients: 'Pechuga de pollo, espinaca picada salteada, queso mozzarella hilado, rebozado fino.',
    prepDesc: 'Ideal para horno medio o plancha tapada durante 15-18 minutos. Una opción nutritiva para el día a día.',
    prepTime: '18 min',
    price: 14900,
    priceHalf: 7900,
    unitType: 'peso',
    img: '',
    emoji: '🥬',
    tags: ['saludable'],
    hot: false,
    rating: 4.7
  },
  {
    id: 7,
    cat: 'pollo-rebozado',
    name: 'Hamburguesas caseras de Pollo',
    desc: 'Hamburguesas artesanales de pechuga de pollo, jugosas y naturales.',
    ingredients: 'Pura pechuga de pollo molida, cebollita de verdeo, huevo y pan rallado suave.',
    prepDesc: 'Cocinar a la plancha a fuego medio-fuerte por 6 minutos de cada lado o al horno por 15 minutos.',
    prepTime: '12 min',
    price: 14900,
    priceHalf: 7900,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?w=400&auto=format&fit=crop&q=80',
    emoji: '🍔',
    tags: ['casero', 'popular'],
    hot: true,
    rating: 5.0
  },
  {
    id: 8,
    cat: 'pollo-rebozado',
    name: 'Hamburguesas caseras de Pollo con jamón y queso',
    desc: 'Hamburguesas caseras gigantes rellenas con jamón cocido y queso mozzarella fundido.',
    ingredients: 'Pechuga de pollo molida de granja, relleno generoso de jamón cocido y queso mozzarella.',
    prepDesc: 'Cocinar en plancha tapada a fuego medio para que el queso funda por completo sin quemar la carne.',
    prepTime: '16 min',
    price: 14900,
    priceHalf: 7900,
    unitType: 'peso',
    img: '',
    emoji: '🧀',
    tags: ['relleno', 'premium'],
    hot: false,
    rating: 4.9
  },
  {
    id: 9,
    cat: 'pollo-rebozado',
    name: 'Albóndigas de Pollo',
    desc: 'Albóndigas suaves y carnosas de pollo, listas para salsas, guisados o fideos.',
    ingredients: 'Pechuga de pollo de granja, perejil fresco, huevo, harina de trigo y sal.',
    prepDesc: 'Cocinar en salsa de tomate hirviendo por 15 minutos o dorar al horno y servir al plato.',
    prepTime: '15 min',
    price: 14900,
    priceHalf: 7900,
    unitType: 'peso',
    img: '',
    emoji: '☄️',
    tags: [],
    hot: false,
    rating: 4.5
  },
  {
    id: 10,
    cat: 'pollo-granja',
    name: 'Arrolladito de Pollo con jamón y mozzarella',
    desc: 'Exquisito arrollado artesanal de pollo fresco relleno con jamón y queso mozzarella.',
    ingredients: 'Pollo de campo deshuesado, abundante jamón cocido, queso mozzarella premium, atado a mano.',
    prepDesc: 'Hornear a fuego medio (180°C) tapado con papel aluminio por 45 minutos, destapar los últimos 15 min para dorar.',
    prepTime: '60 min',
    price: 20900,
    priceHalf: 11000,
    unitType: 'peso',
    img: '',
    emoji: '🌯',
    tags: ['casero', 'premium'],
    hot: false,
    rating: 4.8
  },
  {
    id: 11,
    cat: 'pollo-granja',
    name: 'Arrolladito de Pollo con Roquefort',
    desc: 'Arrollado de pollo premium relleno con jamón, mozzarella y el inconfundible sabor del queso azul.',
    ingredients: 'Pollo deshuesado seleccionado, jamón, mozzarella y queso azul desmenuzado de sabor intenso.',
    prepDesc: 'Hornear envuelto en papel aluminio por 45 min a 180°C. Dejar dorar al final. El queso azul le da un toque gourmet único.',
    prepTime: '60 min',
    price: 20900,
    priceHalf: 11000,
    unitType: 'peso',
    img: '',
    emoji: '🧀',
    tags: ['fuerte', 'gourmet'],
    hot: false,
    rating: 4.9
  },
  {
    id: 12,
    cat: 'pollo-granja',
    name: 'Pollo entero',
    desc: 'Pollo de granja entero seleccionado, fresco, limpio y listo para el horno o la parrilla.',
    ingredients: 'Pollo de campo seleccionado de primera calidad.',
    prepDesc: 'Hornear con manteca y limón a 200°C durante 1 hora y cuato, o asar a las brasas de carbón y leña.',
    prepTime: '75 min',
    price: 7900,
    priceHalf: 4200,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1587593817642-87a79e51f901?w=400&auto=format&fit=crop&q=80',
    emoji: '🐔',
    tags: ['fresco'],
    hot: false,
    rating: 4.7
  },
  {
    id: 13,
    cat: 'pollo-granja',
    name: 'Filet de Pechuga',
    desc: 'Filetes limpios, tiernos y sin grasa de pura pechuga de pollo de primera selección.',
    ingredients: 'Pechuga de pollo fresca de granja deshuesada y desgrasada.',
    prepDesc: 'Ideal para cocinar a la plancha con limón, cortar en tiritas para ensaladas o saltear con verduras.',
    prepTime: '10 min',
    price: 14900,
    priceHalf: 7900,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&auto=format&fit=crop&q=80',
    emoji: '🥩',
    tags: ['fresco', 'magro'],
    hot: true,
    rating: 4.9
  },
  {
    id: 14,
    cat: 'pollo-granja',
    name: 'Filet de Pata muslo',
    desc: 'Cortes limpios y deshuesados de pata muslo, la opción más jugosa de la granja.',
    ingredients: 'Muslo y pata de pollo deshuesados frescos de primera calidad.',
    prepDesc: 'Excelente para la plancha a fuego medio-alto por 12 minutos o para guisados carnosos súper tiernos.',
    prepTime: '12 min',
    price: 14900,
    priceHalf: 7900,
    unitType: 'peso',
    img: '',
    emoji: '🥩',
    tags: ['jugoso'],
    hot: false,
    rating: 4.7
  },
  {
    id: 15,
    cat: 'pollo-granja',
    name: 'Pata muslo',
    desc: 'Pata muslo fresca seleccionada con piel, ideal para parrilladas o el horno.',
    ingredients: 'Cortes seleccionados de pata muslo fresca con hueso.',
    prepDesc: 'Hornear a fuego medio con papas y cebollas por 45 minutos o asar lentamente en la parrilla.',
    prepTime: '45 min',
    price: 7900,
    priceHalf: 4200,
    unitType: 'peso',
    img: '',
    emoji: '🍗',
    tags: ['económico'],
    hot: false,
    rating: 4.6
  },
  {
    id: 16,
    cat: 'pollo-granja',
    name: 'Pata muslo sin piel',
    desc: 'Corte de pata muslo magro, limpio y sin piel. Sabor jugoso y bajo en grasas.',
    ingredients: 'Cortes de pata muslo sin piel frescos de granja.',
    prepDesc: 'Ideal para dietas saludables. Cocinar al horno con hierbas provenzales o a la plancha.',
    prepTime: '35 min',
    price: 7900,
    priceHalf: 4200,
    unitType: 'peso',
    img: '',
    emoji: '🍗',
    tags: ['saludable', 'sin-piel'],
    hot: false,
    rating: 4.7
  },
  {
    id: 17,
    cat: 'pollo-rebozado',
    name: 'Supremas de Pechuga',
    desc: 'Supremas súper carnosas rebozadas de pura pechuga de pollo de primera calidad.',
    ingredients: 'Filet de pechuga seleccionado, huevo batido aromatizado, rebozado fino crujiente.',
    prepDesc: 'Cocinar al horno en placa aceitada a fuego fuerte por 15 minutos o freír en aceite abundante.',
    prepTime: '15 min',
    price: 14900,
    priceHalf: 7900,
    priceUnit: 3500,
    unitType: 'mixto',
    img: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&auto=format&fit=crop&q=80',
    emoji: '🍗',
    tags: ['popular', 'magro'],
    hot: true,
    rating: 5.0
  },
  {
    id: 18,
    cat: 'pollo-rebozado',
    name: 'Supremas de Pata muslo',
    desc: 'Supremas de pata muslo deshuesada rebozadas, la combinación perfecta de jugo y rebozado.',
    ingredients: 'Filet de pata muslo seleccionado, huevo, rebozado clásico de la casa.',
    prepDesc: 'Hornear a fuego fuerte por 18 minutos. Al ser carne de muslo, queda extremadamente jugosa por dentro.',
    prepTime: '18 min',
    price: 14900,
    priceHalf: 7900,
    priceUnit: 3500,
    unitType: 'mixto',
    img: '',
    emoji: '🍗',
    tags: ['jugoso'],
    hot: false,
    rating: 4.8
  },
  {
    id: 19,
    cat: 'pollo-rebozado',
    name: 'Supremas rellenas con jamón y mozzarella',
    desc: 'Supremas gigantes de pechuga de pollo rellenas con jamón y abundante queso mozzarella fundido.',
    ingredients: 'Pechuga de pollo grande, jamón cocido premium, queso mozzarella hilado, rebozado crujiente.',
    prepDesc: 'Recomendado cocinar al horno a fuego medio (180°C) durante 22-25 minutos para que caliente el corazón de queso.',
    prepTime: '25 min',
    price: 20900,
    priceHalf: 11000,
    priceUnit: 5900,
    unitType: 'mixto',
    img: '',
    emoji: '🧀',
    tags: ['popular', 'relleno', 'premium'],
    hot: true,
    rating: 5.0
  },
  {
    id: 20,
    cat: 'pollo-granja',
    name: 'Pollo deshuesado',
    desc: 'Pollo de granja entero deshuesado a mano, ideal para arrollados caseros rellenos.',
    ingredients: 'Pollo entero fresco seleccionado, deshuesado artesanalmente.',
    prepDesc: 'Rellenar con jamón, queso, morrones y huevo. Atar con hilo de cocina y hornear por 1 hora.',
    prepTime: '60 min',
    price: 19900,
    priceHalf: 10500,
    unitType: 'peso',
    img: '',
    emoji: '🐔',
    tags: ['premium'],
    hot: false,
    rating: 4.8
  },
  {
    id: 21,
    cat: 'pescados-mariscos',
    name: 'Medallones de Merluza',
    desc: 'Medallones rebozados de filet de merluza fresca despinada, ricos y nutritivos.',
    ingredients: 'Filet de merluza molido y moldeado, rebozado tradicional fino.',
    prepDesc: 'Cocinar en horno fuerte por 12-15 minutos o freír por 4 minutos. Una alternativa deliciosa y liviana.',
    prepTime: '12 min',
    price: 16900,
    priceHalf: 8900,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&auto=format&fit=crop&q=80',
    emoji: '🐟',
    tags: ['popular', 'mar'],
    hot: true,
    rating: 4.8
  },
  {
    id: 22,
    cat: 'pescados-mariscos',
    name: 'Medallones de Merluza con espinacas y queso',
    desc: 'Medallones de merluza con espinaca picada salteada y queso derretido por dentro.',
    ingredients: 'Filet de merluza de mar, espinaca de hoja, queso mozzarella, rebozado fino.',
    prepDesc: 'Hornear a temperatura moderada (180°C) por 15 minutos. Saludable, bajo en grasas y con todo el sabor.',
    prepTime: '15 min',
    price: 16900,
    priceHalf: 8900,
    unitType: 'peso',
    img: '',
    emoji: '🥬',
    tags: ['saludable'],
    hot: false,
    rating: 4.6
  },
  {
    id: 23,
    cat: 'pescados-mariscos',
    name: 'Medallones de Merluza Primavera',
    desc: 'Medallones de merluza rebozados con zanahoria rallada, morrón y granos de choclo.',
    ingredients: 'Filet de merluza despinado, choclo amarillo, morrón picado, zanahoria, rebozado especial.',
    prepDesc: 'Recomendado al horno fuerte por 15 minutos. Aporta un toque crujiente y dulce con sus vegetales.',
    prepTime: '15 min',
    price: 16900,
    priceHalf: 8900,
    unitType: 'peso',
    img: '',
    emoji: '🌈',
    tags: [],
    hot: false,
    rating: 4.5
  },
  {
    id: 24,
    cat: 'pescados-mariscos',
    name: 'Medallones de Merluza con roquefort',
    desc: 'Medallones premium rebozados con un toque aromático y sabroso de queso azul.',
    ingredients: 'Filet de merluza seleccionado, queso roquefort desmenuzado premium, rebozado crujiente.',
    prepDesc: 'Cocinar en horno medio por 15 minutos. El queso azul fundido le da un toque gourmet extraordinario.',
    prepTime: '15 min',
    price: 16900,
    priceHalf: 8900,
    unitType: 'peso',
    img: '',
    emoji: '🧀',
    tags: ['gourmet'],
    hot: false,
    rating: 4.8
  },
  {
    id: 47,
    cat: 'pescados-mariscos',
    name: 'Milanesas de Merluza',
    desc: 'Clásicas milanesas de merluza enteras y rebozadas tradicionales, súper tiernas y listas para cocinar.',
    ingredients: 'Filet de merluza fresca limpia y despinada, huevo batido aromatizado, rebozado tradicional fino.',
    prepDesc: 'Cocinar en placa aceitada al horno a fuego máximo por 12-15 minutos o freír por 4 minutos.',
    prepTime: '12 min',
    price: 28000,
    priceHalf: 14900,
    unitType: 'peso',
    img: '',
    emoji: '🐟',
    tags: ['popular', 'mar'],
    hot: false,
    rating: 4.8
  },
  {
    id: 25,
    cat: 'pescados-mariscos',
    name: 'Merluza a las Finas Hierbas',
    desc: 'Filet de merluza entero rebozado con mix aromático de romero, tomillo, albahaca y orégano.',
    ingredients: 'Filet de merluza fresca despinado, huevo, mix de hierbas finas (romero, tomillo, albahaca), rebozado fino.',
    prepDesc: 'Cocinar en placa aceitada al horno a fuego máximo por 12-15 minutos. Exquisito perfume y frescura.',
    prepTime: '12 min',
    price: 28000,
    priceHalf: 14900,
    unitType: 'peso',
    img: '',
    emoji: '🌿',
    tags: ['aromático'],
    hot: false,
    rating: 4.7
  },
  {
    id: 26,
    cat: 'pescados-mariscos',
    name: 'Merluza a la Romana (lampreado)',
    desc: 'Filet de merluza fresco rebozado en una capa esponjosa tradicional de huevo batido.',
    ingredients: 'Filet de merluza despinado, masa aireada de huevo batido, harina, pizca de soda.',
    prepDesc: 'Ideal para freír en abundante aceite caliente por 4 minutos hasta inflar y dorar, servir con limón fresco.',
    prepTime: '5 min',
    price: 28000,
    priceHalf: 14900,
    unitType: 'peso',
    img: '',
    emoji: '🐟',
    tags: ['tradicional', 'popular'],
    hot: true,
    rating: 4.9
  },
  {
    id: 27,
    cat: 'pescados-mariscos',
    name: 'Crocantes de Merluza',
    desc: 'Bocaditos crocantes de merluza tipo nuggets, crujientes por fuera y tiernos por dentro.',
    ingredients: 'Merluza despinada de mar procesada, rebozado crocante dorado con cereales.',
    prepDesc: 'Freír por 3 minutos o dorar al horno fuerte por 10 minutos. Ideales para picadas o menú infantil.',
    prepTime: '10 min',
    price: 28000,
    priceHalf: 14900,
    unitType: 'peso',
    img: '',
    emoji: '🐟',
    tags: ['niños'],
    hot: false,
    rating: 4.7
  },
  {
    id: 28,
    cat: 'pescados-mariscos',
    name: 'Rodajas Merluza naturales',
    desc: 'Rodajas de merluza fresca seleccionada natural, ideal para salsas, chupín o al vapor.',
    ingredients: 'Rodajas gruesas de merluza fresca natural con espina.',
    prepDesc: 'Cocinar en salsa de tomate por 20 minutos o asar al horno con aceite de oliva y verduras juliana.',
    prepTime: '20 min',
    price: 19900,
    priceHalf: 10500,
    unitType: 'peso',
    img: '',
    emoji: '🐟',
    tags: ['natural'],
    hot: false,
    rating: 4.6
  },
  {
    id: 29,
    cat: 'pescados-mariscos',
    name: 'Filet de Merluza',
    desc: 'Filetes seleccionados y limpios de merluza fresca, listos para milanesas o al horno.',
    ingredients: 'Filet de merluza fresco despinado y limpio de mar.',
    prepDesc: 'Ideal para rebozar en casa o cocinar al horno con rodajas de tomate, cebolla y queso cremoso.',
    prepTime: '15 min',
    price: 15900,
    priceHalf: 8500,
    unitType: 'peso',
    img: '',
    emoji: '🐟',
    tags: ['fresco', 'popular'],
    hot: true,
    rating: 4.9
  },
  {
    id: 30,
    cat: 'pescados-mariscos',
    name: 'Filet de Atún',
    desc: 'Filetes de atún jugosos y de excelente espesor, ideales para la plancha o grill.',
    ingredients: 'Filet de atún carnoso seleccionado de primera calidad.',
    prepDesc: 'Cocinar a la plancha lubricada muy caliente por 3-4 minutos de cada lado para conservar la jugosidad.',
    prepTime: '8 min',
    price: 27900,
    priceHalf: 14800,
    unitType: 'peso',
    img: '',
    emoji: '🐟',
    tags: ['gourmet'],
    hot: false,
    rating: 4.8
  },
  {
    id: 31,
    cat: 'pescados-mariscos',
    name: 'Rabas',
    desc: 'Anillos tiernos de calamar seleccionados listos para enharinar y freír en casa.',
    ingredients: 'Anillos limpios y tiernizados de tubo de calamar premium.',
    prepDesc: 'Pasar por harina común y freír en abundante aceite hirviendo por exactamente 1 minuto y medio para que queden tiernas.',
    prepTime: '2 min',
    price: 57000,
    priceHalf: 29900,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&auto=format&fit=crop&q=80',
    emoji: '⭕',
    tags: ['popular', 'premium'],
    hot: true,
    rating: 5.0
  },
  {
    id: 32,
    cat: 'pescados-mariscos',
    name: 'Cazuela de Mariscos x 500gr',
    desc: 'Pote de 500 gramos de mix premium de mariscos seleccionados (langostinos, mejillones, calamar) para cazuelas de nivel.',
    ingredients: 'Langostinos pelados, mejillones pelados, anillos de calamar, vieiras seleccionadas.',
    prepDesc: 'Cocinar en salsa de tomate y vino blanco por 8-10 minutos al final de la preparación. Un deleite gourmet.',
    prepTime: '10 min',
    price: 26000,
    unitType: 'unidad',
    img: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400&auto=format&fit=crop&q=80',
    emoji: '🥘',
    tags: ['premium', 'gourmet'],
    hot: true,
    rating: 4.9
  },
  {
    id: 33,
    cat: 'bocados-papas',
    name: 'Bocaditos de Calabaza con mozzarella',
    desc: 'Esferas crujientes rellenas de puré dulce de calabaza y queso mozzarella hilado.',
    ingredients: 'Puré de calabaza seleccionado, queso mozzarella fresca, rebozado fino dorado.',
    prepDesc: 'Hornear a temperatura máxima por 10 minutos para lograr una corteza crujiente y queso fundido.',
    prepTime: '10 min',
    price: 15900,
    priceHalf: 8500,
    unitType: 'peso',
    img: '',
    emoji: '🟡',
    tags: ['niños', 'vegetariana'],
    hot: false,
    rating: 4.8
  },
  {
    id: 34,
    cat: 'bocados-papas',
    name: 'Bastones de mozzarella',
    desc: 'Bastones crujientes rellenos de puro queso mozzarella que estalla al morder.',
    ingredients: 'Bastones macizos de queso mozzarella hilada, doble rebozado crujiente.',
    prepDesc: 'Hornear en placa aceitada muy caliente por 8 minutos a temperatura máxima para evitar fugas de queso.',
    prepTime: '8 min',
    price: 15900,
    priceHalf: 8500,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1531749668029-2db88e4b76ce?w=400&auto=format&fit=crop&q=80',
    emoji: '🧀',
    tags: ['popular', 'queso'],
    hot: true,
    rating: 4.9
  },
  {
    id: 35,
    cat: 'bocados-papas',
    name: 'Tequeños',
    desc: 'Deditos venezolanos artesanales rellenos de queso blanco fundente envueltos en masa crujiente.',
    ingredients: 'Masa de harina de trigo hojaldrada casera, bastón generoso de queso semiduro.',
    prepDesc: 'Hornear en horno precalentado a 200°C por 10 minutos o freír en aceite hasta dorar la masa.',
    prepTime: '10 min',
    price: 15900,
    priceHalf: 8500,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=400&auto=format&fit=crop&q=80',
    emoji: '🫔',
    tags: ['queso', 'popular'],
    hot: true,
    rating: 4.9
  },
  {
    id: 36,
    cat: 'veggie-soja',
    name: 'Hamburguesas caseras de Lentejas rellenas con mozzarella',
    desc: 'Hamburguesas de lentejas artesanales de alto valor nutricional rellenas con queso.',
    ingredients: 'Lentejas cocidas, cebolla de verdeo, avena, huevo y relleno de mozzarella.',
    prepDesc: 'Cocinar a fuego medio en plancha lubricada por 5 minutos por lado. Súper saludables y sabrosas.',
    prepTime: '10 min',
    price: 15900,
    priceHalf: 8500,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=400&auto=format&fit=crop&q=80',
    emoji: '🌿',
    tags: ['vegetariana', 'saludable'],
    hot: true,
    rating: 4.8
  },
  {
    id: 37,
    cat: 'veggie-soja',
    name: 'Hamburguesas caseras de Garbanzos rellenas con mozzarella',
    desc: 'Hamburguesas ricas en proteínas hechas de garbanzo con un tierno centro de mozzarella.',
    ingredients: 'Garbanzos molidos cocidos, perejil, ajo y corazón de queso mozzarella hilado.',
    prepDesc: 'Cocinar a la plancha a fuego medio por 5 minutos de cada lado. Excelente opción para acompañar ensaladas.',
    prepTime: '10 min',
    price: 15900,
    priceHalf: 8500,
    unitType: 'peso',
    img: '',
    emoji: '🍔',
    tags: ['vegetariana', 'saludable'],
    hot: false,
    rating: 4.7
  },
  {
    id: 38,
    cat: 'veggie-soja',
    name: 'Milanesas de Soja',
    desc: 'Clásica milanesa de soja por unidad, baja en grasas, rica en fibras y proteínas vegetales.',
    ingredients: 'Harina de soja orgánica seleccionada y rebozado fino.',
    prepDesc: 'Cocinar al horno en placa ligeramente lubricada por 10 minutos. Rápido, práctico y saludable.',
    prepTime: '10 min',
    price: 1800,
    unitType: 'unidad',
    img: '',
    emoji: '🌱',
    tags: ['vegetariana', 'económico'],
    hot: false,
    rating: 4.5
  },
  {
    id: 39,
    cat: 'veggie-soja',
    name: 'Milanesas de Soja con espinacas y queso',
    desc: 'Milanesa de soja por unidad cubierta con una capa cremosa de espinaca picada salteada y queso mozzarella.',
    ingredients: 'Base de soja seleccionada, cubierta de espinacas cocidas finas y mozzarella fundida.',
    prepDesc: 'Cocinar al horno por 12 minutos hasta dorar la superficie. Nutritivas, ideales para las comidas familiares.',
    prepTime: '12 min',
    price: 1800,
    unitType: 'unidad',
    img: '',
    emoji: '🥬',
    tags: ['vegetariana'],
    hot: false,
    rating: 4.7
  },
  {
    id: 40,
    cat: 'veggie-soja',
    name: 'Milanesas de Soja con calabaza',
    desc: 'Milanesa gourmet de soja por unidad coronada con suave puré de calabaza y mozzarella.',
    ingredients: 'Base de soja seleccionada, puré de calabaza dulce natural, queso mozzarella fresca.',
    prepDesc: 'Hornear a fuego fuerte por 10-12 minutos para gratinar el queso sobre el puré dulce de calabaza.',
    prepTime: '12 min',
    price: 1800,
    unitType: 'unidad',
    img: '',
    emoji: '🎃',
    tags: ['vegetariana'],
    hot: false,
    rating: 4.6
  },
  {
    id: 41,
    cat: 'bocados-papas',
    name: 'Canastitas Humita',
    desc: 'Canastitas de masa hojaldrada abiertas rellenas de choclo amarillo cremoso y queso.',
    ingredients: 'Masa de hojaldre casera, choclo rallado amarillo dulce, salsa bechamel suave, queso.',
    prepDesc: 'Hornear a temperatura fuerte (200°C) por 12-15 minutos en placa limpia hasta dorar los bordes.',
    prepTime: '15 min',
    price: 2500,
    unitType: 'unidad',
    img: '',
    emoji: '🥧',
    tags: ['vegetariana'],
    hot: false,
    rating: 4.6
  },
  {
    id: 42,
    cat: 'bocados-papas',
    name: 'Canastitas acelga y queso',
    desc: 'Canastitas de hojaldre rellenas de acelga tierna cocida con salsa bechamel y parmesano.',
    ingredients: 'Masa de hojaldre, acelga picada salteada, salsa bechamel, queso mozzarella y parmesano.',
    prepDesc: 'Hornear a 200°C por 12-15 minutos. Una canastita con relleno sabroso, cremoso y verde.',
    prepTime: '15 min',
    price: 2500,
    unitType: 'unidad',
    img: '',
    emoji: '🥧',
    tags: ['vegetariana'],
    hot: false,
    rating: 4.5
  },
  {
    id: 43,
    cat: 'bocados-papas',
    name: 'Papas McCain Bastón Tradicional x 500grs',
    desc: 'Bolsa de papas fritas congeladas McCain tradicionales x 500grs de excelente corte y crujido.',
    ingredients: 'Papas seleccionadas cortadas y prefritas congeladas de origen certificado McCain.',
    prepDesc: 'Freír en aceite muy caliente por 4 minutos o dorar al horno sin descongelar a temperatura máxima por 15 minutos.',
    prepTime: '15 min',
    price: 8000,
    unitType: 'unidad',
    img: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=400&auto=format&fit=crop&q=80',
    emoji: '🍟',
    tags: ['marca-premium'],
    hot: false,
    rating: 4.8
  },
  {
    id: 44,
    cat: 'bocados-papas',
    name: 'Papas McCain Noisette x 500grs',
    desc: 'Deliciosas esferas de puré de papa congelado McCain, súper crocantes por fuera (500g).',
    ingredients: 'Puré de papas McCain moldeado en esferas noisette congeladas.',
    prepDesc: 'Hornear a temperatura máxima por 15 minutos o freír. El complemento divertido y delicioso para cualquier plato.',
    prepTime: '15 min',
    price: 8000,
    unitType: 'unidad',
    img: '',
    emoji: '🍟',
    tags: ['marca-premium'],
    hot: false,
    rating: 4.7
  },
  {
    id: 45,
    cat: 'almacen-huevos',
    name: 'Huevos blancos grandes # 0',
    desc: 'Huevo blanco extra grande seleccionado # 0, súper fresco de granja (se vende por unidad).',
    ingredients: 'Huevos blancos de campo de primera calidad fresca.',
    prepDesc: 'Conservar en lugar fresco. Ideales para tortillas, repostería o revueltos nutritivos cotidianos.',
    prepTime: 'fresco',
    price: 350,
    unitType: 'unidad',
    img: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=400&auto=format&fit=crop&q=80',
    emoji: '🥚',
    tags: ['granja', 'fresco'],
    hot: true,
    rating: 4.9
  },
  {
    id: 46,
    cat: 'almacen-huevos',
    name: 'Huevos Bandeja x 20 unidades',
    desc: 'Bandeja de cartón con 20 unidades de huevos blancos seleccionados gigantes, ahorro familiar.',
    ingredients: 'Bandeja de cartón con 20 unidades de huevos de campo extra grandes.',
    prepDesc: 'La opción de ahorro perfecta para el hogar. Conservar refrigerados o en ambiente fresco.',
    prepTime: 'fresco',
    price: 7000,
    unitType: 'unidad',
    img: '',
    emoji: '🥚',
    tags: ['granja', 'ahorro'],
    hot: false,
    rating: 4.8
  }
];

// Ajustar dinámicamente el precio de medio kilo para que sea exactamente la mitad del precio del kilo
MENU.forEach(item => {
  if (item.price && (item.unitType === 'peso' || item.unitType === 'mixto')) {
    item.priceHalf = Math.round(item.price / 2);
  }
});