// ─── CONFIGURACIÓN DE PUNTO 25 DELIVERY ───────────────────────────────────
const WA_NUMBERS = ['3813253754', '3813980410']; // Teléfonos de contacto del catálogo
const INSTAGRAM_USER = 'punto25delivery';
const ADDRESS_TEXT = 'Corrientes 664, Barrio Norte';

const MENU = [
  // ── CATEGORÍA: REBOZADOS DE POLLO (pollo-rebozado) ──────────────────────────
  {
    id: 1,
    cat: 'pollo-rebozado',
    name: 'Patitas de Pollo',
    desc: 'Clásicas patitas rebozadas súper crocantes, ideales para los más chicos.',
    price: 5800,
    priceHalf: 3100,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=300&auto=format&fit=crop&q=60',
    emoji: '🍗',
    tags: ['popular', 'niños'],
    hot: true,
    rating: 4.9
  },
  {
    id: 2,
    cat: 'pollo-rebozado',
    name: 'Patitas con jamón y queso',
    desc: 'Patitas crujientes rellenas con exquisito jamón y queso derretido.',
    price: 6400,
    priceHalf: 3400,
    unitType: 'peso',
    img: '',
    emoji: '🧀',
    tags: ['popular', 'relleno'],
    hot: false,
    rating: 4.8
  },
  {
    id: 3,
    cat: 'pollo-rebozado',
    name: 'Crocantes de Pollo (Nuggets)',
    desc: 'Bocaditos de pechuga de pollo rebozados con un rebozado extra crujiente.',
    price: 6000,
    priceHalf: 3200,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=300&auto=format&fit=crop&q=60',
    emoji: '🍗',
    tags: ['crocante'],
    hot: true,
    rating: 4.9
  },
  {
    id: 4,
    cat: 'pollo-rebozado',
    name: 'Medallones de Pollo',
    desc: 'Prácticos y deliciosos medallones de pollo listos para la plancha o el horno.',
    price: 5200,
    priceHalf: 2800,
    unitType: 'peso',
    img: '',
    emoji: '💿',
    tags: ['exprés'],
    hot: false,
    rating: 4.6
  },
  {
    id: 5,
    cat: 'pollo-rebozado',
    name: 'Medallones de Pollo con jamón y queso',
    desc: 'Medallones rellenos de jamón y queso hilado de primera calidad.',
    price: 5800,
    priceHalf: 3100,
    unitType: 'peso',
    img: '',
    emoji: '🧀',
    tags: ['relleno'],
    hot: false,
    rating: 4.7
  },
  {
    id: 6,
    cat: 'pollo-rebozado',
    name: 'Medallones de Pollo con espinacas y queso',
    desc: 'Una opción equilibrada y sabrosa con espinaca fresca y queso derretido.',
    price: 5800,
    priceHalf: 3100,
    unitType: 'peso',
    img: '',
    emoji: '🥬',
    tags: ['saludable'],
    hot: false,
    rating: 4.7
  },
  {
    id: 7,
    cat: 'pollo-rebozado',
    name: 'Hamburguesas caseras de Pollo',
    desc: 'Elaboradas artesanalmente con pura pechuga de pollo y condimentos especiales.',
    price: 5900,
    priceHalf: 3150,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?w=300&auto=format&fit=crop&q=60',
    emoji: '🍔',
    tags: ['casero', 'popular'],
    hot: true,
    rating: 5.0
  },
  {
    id: 8,
    cat: 'pollo-rebozado',
    name: 'Hamburguesas caseras de Pollo con jamón y queso',
    desc: 'Hamburguesas artesanales rellenas de abundante jamón y queso mozzarella.',
    price: 6500,
    priceHalf: 3500,
    unitType: 'peso',
    img: '',
    emoji: '🧀',
    tags: ['relleno', 'premium'],
    hot: false,
    rating: 4.9
  },
  {
    id: 9,
    cat: 'pollo-rebozado',
    name: 'Albóndigas de Pollo',
    desc: 'Albóndigas suaves y sabrosas, ideales para acompañar con salsas o pastas.',
    price: 5400,
    priceHalf: 2900,
    unitType: 'peso',
    img: '',
    emoji: '☄️',
    tags: [],
    hot: false,
    rating: 4.5
  },
  {
    id: 17,
    cat: 'pollo-rebozado',
    name: 'Supremas de Pechuga',
    desc: 'Supremas súper tiernas y magras rebozadas listas para cocinar.',
    price: 7500,
    priceHalf: 3950,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=300&auto=format&fit=crop&q=60',
    emoji: '🍗',
    tags: ['popular', 'magro'],
    hot: true,
    rating: 5.0
  },
  {
    id: 18,
    cat: 'pollo-rebozado',
    name: 'Supremas de Pata muslo',
    desc: 'Supremas súper jugosas de pata muslo deshuesada y rebozada.',
    price: 7100,
    priceHalf: 3750,
    unitType: 'peso',
    img: '',
    emoji: '🍗',
    tags: ['jugoso'],
    hot: false,
    rating: 4.8
  },
  {
    id: 19,
    cat: 'pollo-rebozado',
    name: 'Supremas rellenas con jamón y mozzarella',
    desc: 'Supremas gigantes de pechuga de pollo rellenas con jamón y abundante queso derretido.',
    price: 8500,
    priceHalf: 4500,
    unitType: 'peso',
    img: '',
    emoji: '🧀',
    tags: ['popular', 'relleno', 'premium'],
    hot: true,
    rating: 5.0
  },

  // ── CATEGORÍA: GRANJA Y FRESCOS (pollo-granja) ─────────────────────────────
  {
    id: 10,
    cat: 'pollo-granja',
    name: 'Arrolladito de Pollo con jamón y mozzarella',
    desc: 'Exquisito arrollado artesanal relleno. Listo para hornear.',
    price: 7800,
    unitType: 'unidad',
    img: '',
    emoji: '🌯',
    tags: ['casero', 'premium'],
    hot: false,
    rating: 4.8
  },
  {
    id: 11,
    cat: 'pollo-granja',
    name: 'Arrolladito de Pollo con Roquefort',
    desc: 'Arrollado artesanal con jamón, mozzarella y un toque de queso azul intenso.',
    price: 8200,
    unitType: 'unidad',
    img: '',
    emoji: '🧀',
    tags: ['fuerte', 'gourmet'],
    hot: false,
    rating: 4.9
  },
  {
    id: 12,
    cat: 'pollo-granja',
    name: 'Pollo entero',
    desc: 'Pollo entero de campo seleccionado, fresco y limpio.',
    price: 9500,
    unitType: 'unidad',
    img: 'https://images.unsplash.com/photo-1587593817642-87a79e51f901?w=300&auto=format&fit=crop&q=60',
    emoji: '🐔',
    tags: ['fresco'],
    hot: false,
    rating: 4.7
  },
  {
    id: 13,
    cat: 'pollo-granja',
    name: 'Filet de Pechuga',
    desc: 'Filetes limpios y magros de pura pechuga de pollo de primera calidad.',
    price: 7200,
    priceHalf: 3800,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=300&auto=format&fit=crop&q=60',
    emoji: '🥩',
    tags: ['fresco', 'magro'],
    hot: true,
    rating: 4.9
  },
  {
    id: 14,
    cat: 'pollo-granja',
    name: 'Filet de Pata muslo',
    desc: 'Filetes de pata muslo deshuesada, listos para la plancha, súper tiernos.',
    price: 6800,
    priceHalf: 3600,
    unitType: 'peso',
    img: '',
    emoji: '🥩',
    tags: ['jugoso'],
    hot: false,
    rating: 4.7
  },
  {
    id: 15,
    cat: 'pollo-granja',
    name: 'Pata muslo',
    desc: 'Cortes clásicos frescos y carnosos para la parrilla u horno.',
    price: 4200,
    priceHalf: 2200,
    unitType: 'peso',
    img: '',
    emoji: '🍗',
    tags: ['económico'],
    hot: false,
    rating: 4.6
  },
  {
    id: 16,
    cat: 'pollo-granja',
    name: 'Pata muslo sin piel',
    desc: 'Opción más saludable y limpia de pata muslo, lista para condimentar.',
    price: 4600,
    priceHalf: 2400,
    unitType: 'peso',
    img: '',
    emoji: '🍗',
    tags: ['saludable', 'sin-piel'],
    hot: false,
    rating: 4.7
  },
  {
    id: 20,
    cat: 'pollo-granja',
    name: 'Pollo deshuesado',
    desc: 'Pollo deshuesado entero, ideal para rellenar a gusto.',
    price: 7800,
    priceHalf: 4100,
    unitType: 'peso',
    img: '',
    emoji: '🐔',
    tags: ['premium'],
    hot: false,
    rating: 4.8
  },

  // ── CATEGORÍA: PESCADOS Y MARISCOS (pescados-mariscos) ──────────────────────
  {
    id: 21,
    cat: 'pescados-mariscos',
    name: 'Medallones de Merluza',
    desc: 'Clásicos medallones de merluza rebozados, ideales para horno o sartén.',
    price: 5900,
    priceHalf: 3100,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=300&auto=format&fit=crop&q=60',
    emoji: '🐟',
    tags: ['popular', 'mar'],
    hot: true,
    rating: 4.8
  },
  {
    id: 22,
    cat: 'pescados-mariscos',
    name: 'Medallones de Merluza con espinacas y queso',
    desc: 'Sabrosa combinación de merluza, hojas de espinaca y queso derretido.',
    price: 6400,
    priceHalf: 3400,
    unitType: 'peso',
    img: '',
    emoji: '🥬',
    tags: ['saludable'],
    hot: false,
    rating: 4.6
  },
  {
    id: 23,
    cat: 'pescados-mariscos',
    name: 'Medallones de Merluza Primavera',
    desc: 'Con un mix de vegetales finamente picados (zanahoria, choclo, morrón).',
    price: 6400,
    priceHalf: 3400,
    unitType: 'peso',
    img: '',
    emoji: '🌈',
    tags: [],
    hot: false,
    rating: 4.5
  },
  {
    id: 24,
    cat: 'pescados-mariscos',
    name: 'Medallones de Merluza con roquefort',
    desc: 'Medallones premium con un toque aromático y delicioso de queso azul.',
    price: 6800,
    priceHalf: 3600,
    unitType: 'peso',
    img: '',
    emoji: '🧀',
    tags: ['gourmet'],
    hot: false,
    rating: 4.8
  },
  {
    id: 25,
    cat: 'pescados-mariscos',
    name: 'Milanesas de Merluza a las Finas Hierbas',
    desc: 'Filet de merluza rebozado con un toque especial de romero, tomillo y orégano.',
    price: 6900,
    priceHalf: 3650,
    unitType: 'peso',
    img: '',
    emoji: '🌿',
    tags: ['aromático'],
    hot: false,
    rating: 4.7
  },
  {
    id: 26,
    cat: 'pescados-mariscos',
    name: 'Merluza a la Romana (lampreado)',
    desc: 'Filet de merluza rebozado con una capa esponjosa de huevo y harina tucumana.',
    price: 7400,
    priceHalf: 3900,
    unitType: 'peso',
    img: '',
    emoji: '🐟',
    tags: ['tradicional', 'popular'],
    hot: true,
    rating: 4.9
  },
  {
    id: 27,
    cat: 'pescados-mariscos',
    name: 'Crocantes de Merluza',
    desc: 'Bocaditos crocantes tipo nuggets elaborados con filet de merluza tierna.',
    price: 6200,
    priceHalf: 3300,
    unitType: 'peso',
    img: '',
    emoji: '🐟',
    tags: ['niños'],
    hot: false,
    rating: 4.7
  },
  {
    id: 28,
    cat: 'pescados-mariscos',
    name: 'Rodajas Merluza naturales',
    desc: 'Rodajas de merluza fresca listas para la plancha o chupín tradicional.',
    price: 7900,
    priceHalf: 4150,
    unitType: 'peso',
    img: '',
    emoji: '🐟',
    tags: ['natural'],
    hot: false,
    rating: 4.6
  },
  {
    id: 29,
    cat: 'pescados-mariscos',
    name: 'Filet de Merluza',
    desc: 'El clásico filet de merluza fresco despinado y listo para cocinar.',
    price: 7500,
    priceHalf: 3950,
    unitType: 'peso',
    img: '',
    emoji: '🐟',
    tags: ['fresco', 'popular'],
    hot: true,
    rating: 4.9
  },
  {
    id: 30,
    cat: 'pescados-mariscos',
    name: 'Filet de Atún',
    desc: 'Filet de atún rojo/blanco carnoso y nutritivo de primera calidad.',
    price: 8900,
    priceHalf: 4700,
    unitType: 'peso',
    img: '',
    emoji: '🐟',
    tags: ['gourmet'],
    hot: false,
    rating: 4.8
  },
  {
    id: 31,
    cat: 'pescados-mariscos',
    name: 'Rabas',
    desc: 'Anillos de calamar tiernos listos para pasar por harina y freír. Un clásico de mar.',
    price: 12000,
    priceHalf: 6300,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=300&auto=format&fit=crop&q=60',
    emoji: '⭕',
    tags: ['popular', 'premium'],
    hot: true,
    rating: 5.0
  },
  {
    id: 32,
    cat: 'pescados-mariscos',
    name: 'Cazuela de Mariscos',
    desc: 'Espectacular cazuela con mix de mariscos seleccionados (langostinos, mejillones, calamar).',
    price: 9800,
    unitType: 'unidad',
    img: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=300&auto=format&fit=crop&q=60',
    emoji: '🥘',
    tags: ['premium', 'gourmet'],
    hot: true,
    rating: 4.9
  },

  // ── CATEGORÍA: VEGGIE Y SOJA (veggie-soja) ──────────────────────────────────
  {
    id: 36,
    cat: 'veggie-soja',
    name: 'Burgers de Lentejas rellenas con mozzarella',
    desc: 'Hamburguesas caseras de lentejas súper nutritivas con corazón de mozzarella.',
    price: 5400,
    priceHalf: 2900,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=300&auto=format&fit=crop&q=60',
    emoji: '🌿',
    tags: ['vegetariana', 'saludable'],
    hot: true,
    rating: 4.8
  },
  {
    id: 37,
    cat: 'veggie-soja',
    name: 'Burgers de Garbanzos rellenas con mozzarella',
    desc: 'Hamburguesas vegetarianas de garbanzos bien condimentadas con queso mozzarella.',
    price: 5400,
    priceHalf: 2900,
    unitType: 'peso',
    img: '',
    emoji: '🍔',
    tags: ['vegetariana', 'saludable'],
    hot: false,
    rating: 4.7
  },
  {
    id: 38,
    cat: 'veggie-soja',
    name: 'Milanesas de Soja',
    desc: 'Clásicas milanesas de soja, bajas en grasas y ricas en proteínas.',
    price: 4200,
    priceHalf: 2200,
    unitType: 'peso',
    img: '',
    emoji: '🌱',
    tags: ['vegetariana', 'económico'],
    hot: false,
    rating: 4.5
  },
  {
    id: 39,
    cat: 'veggie-soja',
    name: 'Milanesas de Soja con espinacas y queso',
    desc: 'Milanesas de soja cubiertas con una capa cremosa de espinaca y queso fundido.',
    price: 4800,
    priceHalf: 2550,
    unitType: 'peso',
    img: '',
    emoji: '🥬',
    tags: ['vegetariana'],
    hot: false,
    rating: 4.7
  },
  {
    id: 40,
    cat: 'veggie-soja',
    name: 'Milanesas de Soja con calabaza',
    desc: 'Original y suave combinación de soja con puré dulce de calabaza y queso.',
    price: 4800,
    priceHalf: 2550,
    unitType: 'peso',
    img: '',
    emoji: '🎃',
    tags: ['vegetariana'],
    hot: false,
    rating: 4.6
  },

  // ── CATEGORÍA: BOCADOS Y APERITIVOS (bocados-papas) ──────────────────────────
  {
    id: 33,
    cat: 'bocados-papas',
    name: 'Bocaditos de Calabaza con mozzarella',
    desc: 'Exquisitos bocaditos rebozados rellenos de puré cremoso de calabaza y mozzarella.',
    price: 5200,
    priceHalf: 2800,
    unitType: 'peso',
    img: '',
    emoji: '🟡',
    tags: ['niños', 'vegetariana'],
    hot: false,
    rating: 4.8
  },
  {
    id: 34,
    cat: 'bocados-papas',
    name: 'Bastones de mozzarella',
    desc: 'Bastones crujientes rellenos de puro queso mozzarella hilado súper elástico.',
    price: 6900,
    priceHalf: 3650,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1531749668029-2db88e4b76ce?w=300&auto=format&fit=crop&q=60',
    emoji: '🧀',
    tags: ['popular', 'queso'],
    hot: true,
    rating: 4.9
  },
  {
    id: 35,
    cat: 'bocados-papas',
    name: 'Tequeños',
    desc: 'Deditos de masa artesanal rellenos de delicioso queso blanco venezolano.',
    price: 6500,
    priceHalf: 3450,
    unitType: 'peso',
    img: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=300&auto=format&fit=crop&q=60',
    emoji: '🫔',
    tags: ['queso', 'popular'],
    hot: true,
    rating: 4.9
  },
  {
    id: 41,
    cat: 'bocados-papas',
    name: 'Canastitas de Humita',
    desc: 'Empanadas abiertas rellenas de crema dulce de choclo, cebolla caramelizada y queso.',
    price: 700,
    unitType: 'unidad',
    img: '',
    emoji: '🥧',
    tags: ['vegetariana'],
    hot: false,
    rating: 4.6
  },
  {
    id: 42,
    cat: 'bocados-papas',
    name: 'Canastitas de Acelga y Queso',
    desc: 'Canastitas rellenas de acelga picada, salsa bechamel suave y queso parmesano.',
    price: 700,
    unitType: 'unidad',
    img: '',
    emoji: '🥧',
    tags: ['vegetariana'],
    hot: false,
    rating: 4.5
  },
  {
    id: 43,
    cat: 'bocados-papas',
    name: 'Papas McCain Bastón Tradicional',
    desc: 'Bolsa cerrada de papas fritas congeladas listas para freír u hornear súper crujientes (720g).',
    price: 3200,
    unitType: 'unidad',
    img: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=300&auto=format&fit=crop&q=60',
    emoji: '🍟',
    tags: ['marca-premium'],
    hot: false,
    rating: 4.8
  },
  {
    id: 44,
    cat: 'bocados-papas',
    name: 'Papas McCain Noisette',
    desc: 'Esferas crocantes de puré de papa sazonado. Riquísimas e ideales para horno (500g).',
    price: 3600,
    unitType: 'unidad',
    img: '',
    emoji: '🍟',
    tags: ['marca-premium'],
    hot: false,
    rating: 4.7
  },

  // ── CATEGORÍA: ALMACÉN Y HUEVOS (almacen-huevos) ───────────────────────────
  {
    id: 45,
    cat: 'almacen-huevos',
    name: 'Huevos blancos grandes (Docena)',
    desc: 'Docena de huevos blancos de granja seleccionados, frescos y grandes.',
    price: 2200,
    unitType: 'unidad',
    img: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=300&auto=format&fit=crop&q=60',
    emoji: '🥚',
    tags: ['granja', 'fresco'],
    hot: true,
    rating: 4.9
  },
  {
    id: 46,
    cat: 'almacen-huevos',
    name: 'Huevos Bandeja x 20 unidades',
    desc: 'Bandeja completa de cartón con 20 huevos blancos extra grandes de campo.',
    price: 3500,
    unitType: 'unidad',
    img: '',
    emoji: '🥚',
    tags: ['granja', 'ahorro'],
    hot: false,
    rating: 4.8
  }
];